# Generated by Django 5.0.6 on 2024-06-05 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='مدل ماشین')),
                ('year', models.CharField(max_length=50, verbose_name='سال تولید')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('km', models.CharField(max_length=50, verbose_name='کارکرد')),
                ('price', models.CharField(max_length=50, verbose_name='قیمت')),
                ('created', models.DateField(blank=True, default=datetime.date(2024, 6, 5), verbose_name='تاریخ')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
